### ISSUE TITLE
windows node_env not internal or external command, operable program batch file

### ISSUE THREAD

**Issue by vince-fly** [StevenIseki/react-router-redux-example#11]
npm run dev

node_env not internal or external command, operable program batch file

windows:nt v6.1
node v7.1
npm v3.10
error code elifecycle

**Comment by StevenIseki** [comment]
Hi, I don't have windows to test this, but it should work as long as you can figure out the issue with the npm scripts. I think `rm` is not included in Windows, so the fix will be for me to either add [rimraf](https://github.com/isaacs/rimraf) and use that, or a temporary fix for you, chance `rm` to `rd` for the `npm clean script` https://github.com/StevenIseki/react-router-redux-example/blob/master/package.json#L8

**Comment by vince-fly** [comment]
install npm cross-evn package

package.json
"scripts": {
        "build": "npm run clean && cross-env NODE_ENV=prod webpack",
        "clean": "rm public/bundle.js && rm public/style.css && rm public/vendor.js || true",
        "dev": "cross-env NODE_ENV=dev node server.js | cross-env NODE_ENV=dev webpack-dev-server --port 5000 --inline --hot",
        "test": "cross-env NODE_ENV=dev tape src/tests/index.js",
        "prod": "cross-env NODE_ENV=prod node server.js"
    },

OK!!
