### ISSUE TITLE
Missing npm dependency 'request'?

### ISSUE THREAD

**Issue by coatsbj** [StevenIseki/react-router-redux-example#12]
Hey there,

Thanks for putting this together...really awesome example!  Just FYI, upon running per the instructions in the readme (and npm run dev, etc.), received an error about module 'request' not found.  Traced it down to ./src/api/routes/npmPackages.js, using the request node package there and sure enough, wasn't listed in package.json.

Just thought I'd let you know.
Cheers!

**Comment by svnm** [comment]
Cool thanks @coatsbj for that, I have updated added request to `package.json` in latest version, also moved away from superagent to fetch. 👍
